### ISSUE TITLE
I can't embed OSG into web browsers 

### ISSUE THREAD

**Issue by iWun** [xarray/osgRecipes#17]
Hello,I'm trying to embed OSG into web browsers according to the cookbook,and I can register the plugin successfully,but the browser(IE ,FireFox) always breaks down .Anybody can help me?

**Comment by remoe** [comment]
Hi

The current browsers will no longer support ActiveX/NPAPI. It will be dead. Here you find more information:

http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html
https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/
http://blogs.windows.com/msedgedev/2015/05/06/a-break-from-the-past-part-2-saying-goodbye-to-activex-vbscript-attachevent/

**Comment by iWun** [comment]
Thanks
